version: '3.1'

services: 
  cowrie:
    build: 
      context: ./
      dockerfile: cowrie-dockerfile
    restart: always
    depends_on: 
      - db
    ports:
      - 22:2222

  db:
    build: 
      context: ./
      dockerfile: mysql-dockerfile
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306